### ISSUE TITLE
Issue when trying to run client.

### ISSUE THREAD

**Issue by lightningik** [NotEnoughUpdates/MoulConfig#34]
```
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'moulconfig'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:487)
	at net.minecraft.client.main.Main.main(Main.java:223)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)
Caused by: java.lang.RuntimeException: @Category without @Expose in class io.github.notenoughupdates.moulconfig.test.TestConfig on field private io.github.notenoughupdates.moulconfig.test.TestCategoryA io.github.notenoughupdates.moulconfig.test.TestConfig.testCategoryA
	at io.github.notenoughupdates.moulconfig.internal.Warnings.warn0(Warnings.java:60)
	at io.github.notenoughupdates.moulconfig.internal.Warnings.warn(Warnings.java:64)
	at io.github.notenoughupdates.moulconfig.internal.Warnings.warn(Warnings.java:68)
	at io.github.notenoughupdates.moulconfig.processor.ConfigProcessorDriver.processCategoryMeta(ConfigProcessorDriver.java:145)
	at io.github.notenoughupdates.moulconfig.processor.ConfigProcessorDriver.processConfig(ConfigProcessorDriver.java:176)
	at io.github.notenoughupdates.moulconfig.managed.ManagedConfig.buildProcessor(ManagedConfig.kt:77)
	at io.github.notenoughupdates.moulconfig.managed.ManagedConfig.rebuildConfigProcessor(ManagedConfig.kt:45)
	at io.github.notenoughupdates.moulconfig.managed.ManagedConfig._init_$lambda$1$lambda$0(ManagedConfig.kt:17)
	at java.base/java.util.function.Consumer.lambda$andThen$0(Consumer.java:65)
	at io.github.notenoughupdates.moulconfig.managed.ManagedDataFile.reloadFromFile(ManagedDataFile.kt:62)
	at io.github.notenoughupdates.moulconfig.managed.ManagedDataFile.<init>(ManagedDataFile.kt:47)
	at io.github.notenoughupdates.moulconfig.managed.ManagedDataFile.<init>(ManagedDataFile.kt:20)
Caused by: java.lang.RuntimeException: @Category without @Expose in class io.github.notenoughupdates.moulconfig.test.TestConfig on field private io.github.notenoughupdates.moulconfig.test.TestCategoryA io.github.notenoughupdates.moulconfig.test.TestConfig.testCategoryA

	at io.github.notenoughupdates.moulconfig.managed.ManagedConfig.<init>(ManagedConfig.kt:16)
	at io.github.notenoughupdates.moulconfig.managed.ManagedConfig$Companion.create(ManagedConfig.kt:29)
	at io.github.notenoughupdates.moulconfig.managed.ManagedConfig$Companion.create$default(ManagedConfig.kt:24)
	at io.github.notenoughupdates.moulconfig.test.FabricMain.onInitialize(FabricMain.kt:24)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384)
	... 7 more
```

**Comment by nea89o** [comment]
Hi, does this crash your game or just display the warning? Also is this in your own mod or in the moulconfig devenv?

**Comment by lightningik** [comment]
This crashes my game, and this happens on my own mod devenv.

**Comment by nea89o** [comment]
Use version 3.0.0-beta.11. That one should no longer bundle the test mod on 1.20.

**Comment by nea89o** [comment]
Sorry for that, I pretty much only test this on 1.8.9 since the 1.20 version still not has feature parity with the 1.8.9 one.
